apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: web-ui
    app.kubernetes.io/part-of: cocktail-platform
    app.kubernetes.io/managed-by: argocd
spec:
  to:
    kind: Service
    name: frontend
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
