apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: cocktail-db
  labels:
    app.kubernetes.io/name: cocktail-db
    app.kubernetes.io/part-of: cocktail-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
